---
- name: Configure DNS server
  hosts: dns
  become: true
  roles:
    - dns

- name: Configure DNS clients
  hosts: clients
  become: true
  roles:
    - dns_clients

- name: Configure NTP server
  hosts: ntp
  become: true
  roles:
    - ntp

- name: Configure NTP clients
  hosts: clients
  become: true
  roles:
    - ntp_client

- name: Configure Database server (MariaDB)
  hosts: database
  become: true
  roles:
    - database

- name: Configure Web server (Apache)
  hosts: web
  become: true
  roles:
    - web

- name: Configure NRPE (monitoring agent)
  hosts: "clients:!nagios:!ansible"
  become: true
  roles:
    - nrpe

- name: Configure Nagios server
  hosts: nagios
  become: true
  roles:
    - nagios

- name: Configure NFS server
  hosts: nfs
  become: true
  roles:
    - nfs_server

- name: Configure AutoFS clients
  hosts: "clients:!nfs"
  become: true
  roles:
    - autofs_client

- name: Configure FTP server
  hosts: ftp
  become: true
  roles:
    - ftp

- name: Configure Docker web app on workers
  hosts: docker_workers
  become: true
  roles:
    - docker_common
    - docker_webapp

- name: Configure Load Balancer (HAProxy)
  hosts: loadbalancer
  become: true
  roles:
    - loadbalancer