---
- name: Configure DNS server
  hosts: dns
  become: true
  roles:
    - dns

- name: Configure DNS clients
  hosts: clients
  become: true
  roles:
    - dns_clients

- name: Configure NTP server
  hosts: ntp
  become: true
  roles:
    - ntp

- name: Configure NTP clients
  hosts: clients
  become: true
  roles:
    - ntp_client

- name: Configure Database server (MariaDB)
  hosts: database
  become: true
  roles:
    - database

- name: Configure Web server (Apache)
  hosts: web
  become: true
  roles:
    - web

- name: Configure NRPE (monitoring agent)
  hosts: "clients:!nagios:!ansible"
  become: true
  roles:
    - nrpe

- name: Configure Nagios server
  hosts: nagios
  become: true
  roles:
    - nagios